#' A Twist brand thematic color palette generator for ggplot
#' 
#' Function to extract Twist colors as hex codes
#'
#' @param ... Character names of Twist colors for each product theme 
#'
green_ngs_palette <- function(...) {
    green_ngs_colors <-  c(
      `NGS Green`   = "#19805e",
      `UI Green`    = "#04A973",
      `Twist Green` = "#2AD39B",
      `Soft Green`  = "#AAEED7",
      `Light Green` = "#E1F9F1"
    )
  
  cols <- c(...)
  
  if(is.null(cols))
    return(green_ngs_colors)
  
  green_ngs_colors[cols]
  
}

grays_palette <- function(...) {
  grays_colors <-  c(
    `Black`         = "#0F0F10",
    `Primary Slate` = "#232E35",
    `UI Slate`      = "#354652",
    `Medium Gray`   = "#98A8B3",
    `Light Gray `   = "#E0E5EB" 
  )
  
  cols <- c(...)
  
  if(is.null(cols))
    return(grays_colors)
  
  grays_colors[cols]
  
}

blue_oligo_pools_palette <- function(...) {
  blue_oligo_pools_colors <-  c(
    `Deep Teal`  = "#144348",
    `Teal`       = "#2A8E97",
    `Oligo Blue` = "#57C6D0",
    `Sky Teal`   = "#A7E1E6",
    `Light Blue` = "#E7F7F8" 
  )
  
  cols <- c(...)
  
  if(is.null(cols))
    return(blue_oligo_pools_colors)
  
  blue_oligo_pools_colors[cols]
  
}

purple_genes_palette <- function(...) {
  purple_genes_colors <-  c(
    `Sea Purple`   = "#3A30A1",
    `Violet`       = "#4A3FC6",
    `Genes Purple` = "#7676F3",
    `Lilac`        = "#A6A6F7",
    `Light Purple` = "#D5D5FB" 
  )
  
  cols <- c(...)
  
  if(is.null(cols))
    return(purple_genes_colors)
  
  purple_genes_colors[cols]
  
}

pink_biopharma_palette <- function(...) {
  pink_biopharma_colors = c(
    `Fierce Magenta` = "#8911B1",
    `Magenta `       = "#AD15E0",
    `Biopharma Pink` = "#CF6AF1",
    `Rose `          = "#E5B0F8",
    `Light Pink`     = "#F9ECFD" 
  )
  
  cols <- c(...)
  
  if(is.null(cols))
    return(pink_biopharma_colors)
  
  pink_biopharma_colors[cols]
  
}

orange_variant_library_palette <- function(...) {
  orange_variant_library_colors <-  c(
    `Burnt Orange`     = "#8C4608",
    `Deep Orange`      = "#BD5F0A",
    `Orange`           = "#ED770D",
    `Libraries Orange` = "#F49138",
    `Pale Citrus`      = "#F9C79A" 
  )
  
  cols <- c(...)
  
  if(is.null(cols))
    return(orange_variant_library_colors)
  
  orange_variant_library_colors[cols]
  
}

golds_palette <- function(...) {
  golds_colors = c(
    `Gold1`        = "#8E6706",
    `Gold2`        = "#BE8A09",
    `Data Yellow`  = "#EFAD0B",
    `Yellow`       = "#F6BF37",
    `Light Yellow` = "#FBE6B1" 
  )
  
  cols <- c(...)
  
  if(is.null(cols))
    return(golds_colors)
  
  golds_colors[cols]
  
}

#' list of all Twist color palettes
#' 
#' Mother list of all Twist color palettes, generated by calling
#' individual color functions with their default parameters.
#' 
#' @section Available palette names:
#' 
#' "green_ngs", "grays", "blue_oligo_pools", "purple_genes", 
#' "pink_biopharma", "orange_variant_library", "golds"
twist_palettes <- list(
  `green_ngs` = green_ngs_palette(),
  `grays` = grays_palette(),
  `blue_oligo_pools` = blue_oligo_pools_palette(),
  `purple_genes` = purple_genes_palette(),
  `pink_biopharma` = pink_biopharma_palette(),
  `orange_variant_library` = orange_variant_library_palette(),
  `golds` = golds_palette()
)

#' Return function to interpolate a Twist color palette
#'
#' @param palette Character name of palette in twist_palettes for twist_color_pal
#' @param reverse Boolean indicating whether the palette should be reversed
#' @param ... Additional arguments to pass to colorRampPalette()
#'
twist_color_pal <- function(palette = "green_ngs", reverse = FALSE, ...) {
  pal <- twist_palettes[[palette]]
  
  if (reverse) pal <- rev(pal)
  
  colorRampPalette(pal, ...)
}

#' Color scale constructor for twist_color_pal colors
#'
#' @param palette Character name of palette in twist_palettes
#' @param discrete Boolean indicating whether color aesthetic is discrete or not
#' @param reverse Boolean indicating whether the palette should be reversed
#' @param ... Additional arguments passed to discrete_scale() or
#'            scale_color_gradientn(), used respectively when discrete is TRUE or FALSE
#'
scale_color_twist <- function(palette = "green_ngs", discrete = TRUE, reverse = FALSE, ...) {
  pal <- twist_color_pal(palette = palette, reverse = reverse)
  
  if (discrete) {
    discrete_scale("color", paste0(palette, "_palette"), palette = pal, ...)
  } else {
    scale_color_gradientn(colors = pal(256), ...)
  }
}

#' Fill scale constructor for twist_color_pal colors
#'
#' @param palette Character name of palette in twist_palettes
#' @param discrete Boolean indicating whether color aesthetic is discrete or not
#' @param reverse Boolean indicating whether the palette should be reversed
#' @param ... Additional arguments passed to discrete_scale() or
#'            scale_fill_gradientn(), used respectively when discrete is TRUE or FALSE
#'
scale_fill_twist <- function(palette = "green_ngs", discrete = TRUE, reverse = FALSE, ...) {
  pal <- twist_color_pal(palette = palette, reverse = reverse)
  
  if (discrete) {
    discrete_scale("fill", paste0(palette, "_palette"), palette = pal, ...)
  } else {
    scale_fill_gradientn(colors = pal(256), ...)
  }
}
